### PR TITLE
Translations changes

### PR DESCRIPTION
**Pull request by Tiagoquix**
Changes:

- Restored newlines.
- Changed some phrases in the original English version.
- Added translation credits to the `"Announce Timer"` in the Brazilian Portuguese version of the translations.

@Blueberryy [Feel free to add your credits to the Russian translated version of Jailbreak.](https://github.com/Tiagoquix/TF2-Jailbreak-Redux/edit/develop/sourcemod/translations/ru/tf2jail_redux.phrases.txt) Just send me a pull request and I will merge it. Look for the `"Announce Timer"` if you want to add your name.

### CODE REVIEW

**Comment by Blueberryy** [comment]
You don't have to add #format on every translation file and when format code will change, you will need to change it on every file.

**Comment by Tiagoquix** [comment]
> You don't have to add #format on every translation file and when format code will change

Can you please say where did you saw this? I have never seen anyone saying this.
Even the [SourceMod Wiki](https://wiki.alliedmods.net/Translations_(SourceMod_Scripting)#File_Format) does not say anything about not adding the format strings to the translated files.

> and when format code will change, you will need to change it on every file.

This is not a problem. If the author of this plugin changes a format string, he knows he will need to change the translation files too.

**Comment by Blueberryy** [comment]
> > You don't have to add #format on every translation file and when format code will change
> 
> Can you please say where did you saw this? I have never seen anyone saying this.
> Even the [SourceMod Wiki](https://wiki.alliedmods.net/Translations_(SourceMod_Scripting)#File_Format) does not say anything about not adding the format strings to the translated files.

Screenshot_20210205-131513_Chrome
:p
> 
> > and when format code will change, you will need to change it on every file.
> 
> This is not a problem. If the author of this plugin changes a format string, he knows he will need to change the translation files too.

alright

**Comment by Tiagoquix** [comment]
> :p

Oh... my bad. It wasn't explicit. But all right, thanks for the catch. I'll remove the format strings.

**Comment by Tiagoquix** [comment]
Done. The format strings have been removed from the translated files.

**Comment by Scags** [comment]
Looks good. Thanks!

**Pull request merged**
