### PR TITLE
Sort translations by folders and Russian translation with README translation 

### PR DESCRIPTION
**Pull request by Blueberryy**

### CODE REVIEW

**Comment by Tiagoquix** [comment]
Please be consistent and keep the newlines in the phrases files. There is no need to remove them.

You removed some newlines but did keep anothers.

- https://github.com/Scags/TF2-Jailbreak-Redux/pull/141/files#diff-fddacd3dccb096462c2c55f288d8560549903202b7fc05da81b1a700ee5c7957R7
- https://github.com/Scags/TF2-Jailbreak-Redux/pull/141/files?file-filters%5B%5D=.txt#diff-c3b0becec659119a549cc69c269e0fb2cf4eab0baf1d8425e67e8e0de61ebf75R183

Also, by looking at the changes, it seems that you have added new comments. Please, also be consistent with these, adding the new comments to all files or don't add to any of them.

**Comment by Blueberryy** [comment]
> Please be consistent and keep the newlines in the phrases files. There is no need to remove them.
> 
> You removed some newlines but did keep anothers.
> 
> * https://github.com/Scags/TF2-Jailbreak-Redux/pull/141/files#diff-fddacd3dccb096462c2c55f288d8560549903202b7fc05da81b1a700ee5c7957R7
> * https://github.com/Scags/TF2-Jailbreak-Redux/pull/141/files?file-filters%5B%5D=.txt#diff-c3b0becec659119a549cc69c269e0fb2cf4eab0baf1d8425e67e8e0de61ebf75R183
> 
> Also, by looking at the changes, it seems that you have added new comments. Please, also be consistent with these, adding the new comments to all files or don't add to any of them.

Format strings doesn't needed for other languages if original one have it.
And what comments?

**Comment by Tiagoquix** [comment]
> > Please be consistent and keep the newlines in the phrases files. There is no need to remove them.
> > You removed some newlines but did keep anothers.
> > 
> > * https://github.com/Scags/TF2-Jailbreak-Redux/pull/141/files#diff-fddacd3dccb096462c2c55f288d8560549903202b7fc05da81b1a700ee5c7957R7
> > * https://github.com/Scags/TF2-Jailbreak-Redux/pull/141/files?file-filters%5B%5D=.txt#diff-c3b0becec659119a549cc69c269e0fb2cf4eab0baf1d8425e67e8e0de61ebf75R183
> > 
> > Also, by looking at the changes, it seems that you have added new comments. Please, also be consistent with these, adding the new comments to all files or don't add to any of them.
> 
> Format strings doesn't needed for other languages if original one have it.

Afaik, they are. Also, I said about newlines, not format strings. Can you show me where did you see that they aren't necessary?

> And what comments?

Like "// 1: Client name/index". Are they new?

**Comment by Blueberryy** [comment]
> > > Please be consistent and keep the newlines in the phrases files. There is no need to remove them.
> > > You removed some newlines but did keep anothers.
> > > 
> > > * https://github.com/Scags/TF2-Jailbreak-Redux/pull/141/files#diff-fddacd3dccb096462c2c55f288d8560549903202b7fc05da81b1a700ee5c7957R7
> > > * https://github.com/Scags/TF2-Jailbreak-Redux/pull/141/files?file-filters%5B%5D=.txt#diff-c3b0becec659119a549cc69c269e0fb2cf4eab0baf1d8425e67e8e0de61ebf75R183
> > > 
> > > Also, by looking at the changes, it seems that you have added new comments. Please, also be consistent with these, adding the new comments to all files or don't add to any of them.
> > 
> > 
> > Format strings doesn't needed for other languages if original one have it.
> 
> Afaik, they are. Also, I said about newlines, not format strings. Can you show me where did you see that they aren't necessary?
> 
> > And what comments?
> 
> Like "// 1: Client name/index". Are they new?


> Afaik, they are. Also, I said about newlines, not format strings. Can you show me where did you see that they aren't necessary?

Uh just in case i think ^^


> Like "// 1: Client name/index". Are they new?

No. They exist in your official version.
https://github.com/Scags/TF2-Jailbreak-Redux/blob/9abf181656fd5b4599045c84a6142e1f70b6b0aa/sourcemod/translations/tf2jail_redux.phrases.txt#L17

**Comment by Scags** [comment]
Looks good to me. Those nitpicks aren't that big of a problem as long as it works.
Thanks!

**Comment by Blueberryy** [comment]
Thank you, Scags. I dunno what to say about newlines but i can tell that translation is working fine and everyone happy

**Pull request merged**
